CREATE DATABASE todos;

USE todos;

CREATE TABLE todos (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
